Design improvements
solidaridadUY/solidaridaduy.github.io pull request #15
Opened 2020-03-31 15:14 UTC by mrichart

Buenas.
Aprovechando un tiempo libre en una reunión virtual :D ajusté un par de detalles de diseño.
El mas importante, centré un poco mejor el listado.
Además, agrandé la altura del header, me pareció que quedaba un poco mas "lindo".
Vean si les parece bien.

2020-03-31 15:42 UTC, solidaridadUY requested changes

2020-03-31 15:42 UTC, solidaridadUY commented on _sass/header.scss
> +    margin-top: 15px;
Está bueno el header un poco más grande pero hay que agregar alguna regla o elemento que haga que se ajuste la altura del menú hamburguesa en mobile.

2020-03-31 15:44 UTC, solidaridadUY requested changes

2020-03-31 15:44 UTC, solidaridadUY commented on assets/main.scss
> +    display:inline-block;
Creo que esta regla hace que, al ingresar datos, el ancho de los resultados se achique. Hay que pegarle una vichadita extra.

2020-04-01 03:41 UTC, mrichart commented on _sass/header.scss
> +    margin-top: 15px;
De acuerdo. Envío el fix.

2020-04-01 03:43 UTC, mrichart commented on assets/main.scss
> +    display:inline-block;
La idea era que el contenedor del listado se ajuste al tamaño de los datos, para que quede mas centrado.
Va nueva propuesta mas simple.
Aclaro que mis conocimientos de desarrollo web son muuy rudimentarios. Asi que critiquen tramquilos

2020-04-02 21:59 UTC, solidaridadUY approved these changes

2020-04-02 21:59 UTC, merged